/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const AppRole = IDL.Variant({
  'User' : IDL.Null,
  'SuperAdmin' : IDL.Null,
  'Admin' : IDL.Null,
});
export const EntryId = IDL.Nat;
export const VisitorCategory = IDL.Variant({
  'Guest' : IDL.Null,
  'TemporaryEmployee' : IDL.Null,
  'Soldier' : IDL.Null,
  'Employer' : IDL.Null,
  'SpecialGuest' : IDL.Null,
});
export const CheckInInput = IDL.Record({
  'visitorName' : IDL.Text,
  'notes' : IDL.Text,
  'category' : VisitorCategory,
});
export const Timestamp = IDL.Int;
export const CheckIn = IDL.Record({
  'id' : EntryId,
  'submittedBy' : UserId,
  'checkInTime' : Timestamp,
  'isActive' : IDL.Bool,
  'visitorName' : IDL.Text,
  'notes' : IDL.Text,
  'category' : VisitorCategory,
});
export const CheckOut = IDL.Record({
  'checkInId' : EntryId,
  'checkOutTime' : Timestamp,
});
export const EntryRecord = IDL.Record({
  'checkIn' : CheckIn,
  'checkOut' : IDL.Opt(CheckOut),
});
export const UserInfo = IDL.Record({
  'principal' : UserId,
  'role' : AppRole,
  'isActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([UserId, AppRole], [], []),
  'deactivateUser' : IDL.Func([UserId], [], []),
  'deleteEntry' : IDL.Func([EntryId], [], []),
  'editEntry' : IDL.Func([EntryId, CheckInInput], [], []),
  'getActivityLog' : IDL.Func([], [IDL.Vec(EntryRecord)], ['query']),
  'getActivityLogByCategory' : IDL.Func(
      [VisitorCategory],
      [IDL.Vec(EntryRecord)],
      ['query'],
    ),
  'getActivityLogByDateRange' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Vec(EntryRecord)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Opt(AppRole)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'reactivateUser' : IDL.Func([UserId], [], []),
  'revokeRole' : IDL.Func([UserId], [], []),
  'submitCheckIn' : IDL.Func([CheckInInput], [EntryId], []),
  'submitCheckOut' : IDL.Func([EntryId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const AppRole = IDL.Variant({
    'User' : IDL.Null,
    'SuperAdmin' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const EntryId = IDL.Nat;
  const VisitorCategory = IDL.Variant({
    'Guest' : IDL.Null,
    'TemporaryEmployee' : IDL.Null,
    'Soldier' : IDL.Null,
    'Employer' : IDL.Null,
    'SpecialGuest' : IDL.Null,
  });
  const CheckInInput = IDL.Record({
    'visitorName' : IDL.Text,
    'notes' : IDL.Text,
    'category' : VisitorCategory,
  });
  const Timestamp = IDL.Int;
  const CheckIn = IDL.Record({
    'id' : EntryId,
    'submittedBy' : UserId,
    'checkInTime' : Timestamp,
    'isActive' : IDL.Bool,
    'visitorName' : IDL.Text,
    'notes' : IDL.Text,
    'category' : VisitorCategory,
  });
  const CheckOut = IDL.Record({
    'checkInId' : EntryId,
    'checkOutTime' : Timestamp,
  });
  const EntryRecord = IDL.Record({
    'checkIn' : CheckIn,
    'checkOut' : IDL.Opt(CheckOut),
  });
  const UserInfo = IDL.Record({
    'principal' : UserId,
    'role' : AppRole,
    'isActive' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([UserId, AppRole], [], []),
    'deactivateUser' : IDL.Func([UserId], [], []),
    'deleteEntry' : IDL.Func([EntryId], [], []),
    'editEntry' : IDL.Func([EntryId, CheckInInput], [], []),
    'getActivityLog' : IDL.Func([], [IDL.Vec(EntryRecord)], ['query']),
    'getActivityLogByCategory' : IDL.Func(
        [VisitorCategory],
        [IDL.Vec(EntryRecord)],
        ['query'],
      ),
    'getActivityLogByDateRange' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Vec(EntryRecord)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Opt(AppRole)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'reactivateUser' : IDL.Func([UserId], [], []),
    'revokeRole' : IDL.Func([UserId], [], []),
    'submitCheckIn' : IDL.Func([CheckInInput], [EntryId], []),
    'submitCheckOut' : IDL.Func([EntryId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };