/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'User' : null } |
  { 'SuperAdmin' : null } |
  { 'Admin' : null };
export interface CheckIn {
  'id' : EntryId,
  'submittedBy' : UserId,
  'checkInTime' : Timestamp,
  'isActive' : boolean,
  'visitorName' : string,
  'notes' : string,
  'category' : VisitorCategory,
}
export interface CheckInInput {
  'visitorName' : string,
  'notes' : string,
  'category' : VisitorCategory,
}
export interface CheckOut { 'checkInId' : EntryId, 'checkOutTime' : Timestamp }
export type EntryId = bigint;
export interface EntryRecord {
  'checkIn' : CheckIn,
  'checkOut' : [] | [CheckOut],
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserInfo {
  'principal' : UserId,
  'role' : AppRole,
  'isActive' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VisitorCategory = { 'Guest' : null } |
  { 'TemporaryEmployee' : null } |
  { 'Soldier' : null } |
  { 'Employer' : null } |
  { 'SpecialGuest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[UserId, AppRole], undefined>,
  'deactivateUser' : ActorMethod<[UserId], undefined>,
  'deleteEntry' : ActorMethod<[EntryId], undefined>,
  'editEntry' : ActorMethod<[EntryId, CheckInInput], undefined>,
  'getActivityLog' : ActorMethod<[], Array<EntryRecord>>,
  'getActivityLogByCategory' : ActorMethod<
    [VisitorCategory],
    Array<EntryRecord>
  >,
  'getActivityLogByDateRange' : ActorMethod<
    [Timestamp, Timestamp],
    Array<EntryRecord>
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyRole' : ActorMethod<[], [] | [AppRole]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listUsers' : ActorMethod<[], Array<UserInfo>>,
  'reactivateUser' : ActorMethod<[UserId], undefined>,
  'revokeRole' : ActorMethod<[UserId], undefined>,
  'submitCheckIn' : ActorMethod<[CheckInInput], EntryId>,
  'submitCheckOut' : ActorMethod<[EntryId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];