/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export type EntryId = bigint;
export interface CheckOut {
    checkInId: EntryId;
    checkOutTime: Timestamp;
}
export interface CheckIn {
    id: EntryId;
    submittedBy: UserId;
    checkInTime: Timestamp;
    isActive: boolean;
    visitorName: string;
    notes: string;
    category: VisitorCategory;
}
export interface CheckInInput {
    visitorName: string;
    notes: string;
    category: VisitorCategory;
}
export interface EntryRecord {
    checkIn: CheckIn;
    checkOut?: CheckOut;
}
export interface UserInfo {
    principal: UserId;
    role: AppRole;
    isActive: boolean;
}
export enum AppRole {
    User = "User",
    SuperAdmin = "SuperAdmin",
    Admin = "Admin"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VisitorCategory {
    Guest = "Guest",
    TemporaryEmployee = "TemporaryEmployee",
    Soldier = "Soldier",
    Employer = "Employer",
    SpecialGuest = "SpecialGuest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRole(target: UserId, role: AppRole): Promise<void>;
    deactivateUser(target: UserId): Promise<void>;
    deleteEntry(entryId: EntryId): Promise<void>;
    editEntry(entryId: EntryId, input: CheckInInput): Promise<void>;
    getActivityLog(): Promise<Array<EntryRecord>>;
    getActivityLogByCategory(category: VisitorCategory): Promise<Array<EntryRecord>>;
    getActivityLogByDateRange(from: Timestamp, to: Timestamp): Promise<Array<EntryRecord>>;
    getCallerUserRole(): Promise<UserRole>;
    getMyRole(): Promise<AppRole | null>;
    isCallerAdmin(): Promise<boolean>;
    listUsers(): Promise<Array<UserInfo>>;
    reactivateUser(target: UserId): Promise<void>;
    revokeRole(target: UserId): Promise<void>;
    submitCheckIn(input: CheckInInput): Promise<EntryId>;
    submitCheckOut(checkInId: EntryId): Promise<void>;
}
import type { AppRole as _AppRole, CheckIn as _CheckIn, CheckInInput as _CheckInInput, CheckOut as _CheckOut, EntryId as _EntryId, EntryRecord as _EntryRecord, Timestamp as _Timestamp, UserId as _UserId, UserInfo as _UserInfo, UserRole as _UserRole, VisitorCategory as _VisitorCategory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRole(arg0: UserId, arg1: AppRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_AppRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_AppRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deactivateUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return result;
        }
    }
    async deleteEntry(arg0: EntryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEntry(arg0);
            return result;
        }
    }
    async editEntry(arg0: EntryId, arg1: CheckInInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editEntry(arg0, to_candid_CheckInInput_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editEntry(arg0, to_candid_CheckInInput_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getActivityLog(): Promise<Array<EntryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLog();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLog();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityLogByCategory(arg0: VisitorCategory): Promise<Array<EntryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLogByCategory(to_candid_VisitorCategory_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLogByCategory(to_candid_VisitorCategory_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityLogByDateRange(arg0: Timestamp, arg1: Timestamp): Promise<Array<EntryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLogByDateRange(arg0, arg1);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLogByDateRange(arg0, arg1);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<AppRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listUsers(): Promise<Array<UserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async reactivateUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactivateUser(arg0);
            return result;
        }
    }
    async revokeRole(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeRole(arg0);
            return result;
        }
    }
    async submitCheckIn(arg0: CheckInInput): Promise<EntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCheckIn(to_candid_CheckInInput_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCheckIn(to_candid_CheckInInput_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitCheckOut(arg0: EntryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCheckOut(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCheckOut(arg0);
            return result;
        }
    }
}
function from_candid_AppRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_CheckIn_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckIn): CheckIn {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_EntryRecord_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntryRecord): EntryRecord {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserInfo_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserInfo): UserInfo {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_VisitorCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisitorCategory): VisitorCategory {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CheckOut]): CheckOut | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppRole]): AppRole | null {
    return value.length === 0 ? null : from_candid_AppRole_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkIn: _CheckIn;
    checkOut: [] | [_CheckOut];
}): {
    checkIn: CheckIn;
    checkOut?: CheckOut;
} {
    return {
        checkIn: from_candid_CheckIn_n12(_uploadFile, _downloadFile, value.checkIn),
        checkOut: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.checkOut))
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntryId;
    submittedBy: _UserId;
    checkInTime: _Timestamp;
    isActive: boolean;
    visitorName: string;
    notes: string;
    category: _VisitorCategory;
}): {
    id: EntryId;
    submittedBy: UserId;
    checkInTime: Timestamp;
    isActive: boolean;
    visitorName: string;
    notes: string;
    category: VisitorCategory;
} {
    return {
        id: value.id,
        submittedBy: value.submittedBy,
        checkInTime: value.checkInTime,
        isActive: value.isActive,
        visitorName: value.visitorName,
        notes: value.notes,
        category: from_candid_VisitorCategory_n14(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    role: _AppRole;
    isActive: boolean;
}): {
    principal: UserId;
    role: AppRole;
    isActive: boolean;
} {
    return {
        principal: value.principal,
        role: from_candid_AppRole_n20(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Guest: null;
} | {
    TemporaryEmployee: null;
} | {
    Soldier: null;
} | {
    Employer: null;
} | {
    SpecialGuest: null;
}): VisitorCategory {
    return "Guest" in value ? VisitorCategory.Guest : "TemporaryEmployee" in value ? VisitorCategory.TemporaryEmployee : "Soldier" in value ? VisitorCategory.Soldier : "Employer" in value ? VisitorCategory.Employer : "SpecialGuest" in value ? VisitorCategory.SpecialGuest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    User: null;
} | {
    SuperAdmin: null;
} | {
    Admin: null;
}): AppRole {
    return "User" in value ? AppRole.User : "SuperAdmin" in value ? AppRole.SuperAdmin : "Admin" in value ? AppRole.Admin : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserInfo>): Array<UserInfo> {
    return value.map((x)=>from_candid_UserInfo_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EntryRecord>): Array<EntryRecord> {
    return value.map((x)=>from_candid_EntryRecord_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CheckInInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckInInput): _CheckInInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VisitorCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisitorCategory): _VisitorCategory {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    visitorName: string;
    notes: string;
    category: VisitorCategory;
}): {
    visitorName: string;
    notes: string;
    category: _VisitorCategory;
} {
    return {
        visitorName: value.visitorName,
        notes: value.notes,
        category: to_candid_VisitorCategory_n7(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    User: null;
} | {
    SuperAdmin: null;
} | {
    Admin: null;
} {
    return value == AppRole.User ? {
        User: null
    } : value == AppRole.SuperAdmin ? {
        SuperAdmin: null
    } : value == AppRole.Admin ? {
        Admin: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisitorCategory): {
    Guest: null;
} | {
    TemporaryEmployee: null;
} | {
    Soldier: null;
} | {
    Employer: null;
} | {
    SpecialGuest: null;
} {
    return value == VisitorCategory.Guest ? {
        Guest: null
    } : value == VisitorCategory.TemporaryEmployee ? {
        TemporaryEmployee: null
    } : value == VisitorCategory.Soldier ? {
        Soldier: null
    } : value == VisitorCategory.Employer ? {
        Employer: null
    } : value == VisitorCategory.SpecialGuest ? {
        SpecialGuest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
